--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024-2026 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mlancast:create_table_sert_core.sg_application_pages_d endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_tables where owner = upper('sert_core') and table_name = upper('sg_application_pages_d');
create table sert_core.sg_application_pages_d (
    page_wid                number
                            generated by default on null as identity (
                                start with 1 increment by 1 cache 100
                            ),
    application_id          number        not null,
    page_id                 number        not null,
    workspace_id            number        not null,
    workspace               varchar2(255) not null,
    application_name        varchar2(255) not null,
    page_name               varchar2(255) not null,
    complexity_score        number        not null,
    eval_on                 timestamp with local time zone not null,
    constraint sg_application_pages_d_pk primary key (page_wid) rely
);
--rollback drop table sert_core.sg_application_pages_d cascade constraints purge;

--changeset mlancast:create_index_sert_core.sg_application_pages_d_idx1 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:; stripComments:false
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedresult:0 select count(*) from dba_indexes where owner = upper('sert_core') and table_name = upper('sg_application_pages_d') and index_name = upper('sg_application_pages_d_idx1');
create unique index sert_core.sg_application_pages_d_idx1
    on sert_core.sg_application_pages_d (application_id, page_id)
    compress 1;

alter table sert_core.sg_application_pages_d
add constraint sg_application_pages_d_uk
    unique (application_id, page_id)
    using index sert_core.sg_application_pages_d_idx1;
--rollback not required

--changeset mlancast:create_index_sert_core.sg_application_pages_d_idx2 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:; stripComments:false
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedresult:0 select count(*) from dba_indexes where owner = upper('sert_core') and table_name = upper('sg_application_pages_d') and index_name = upper('sg_application_pages_d_idx2');
create index sert_core.sg_application_pages_d_idx2 on sert_core.sg_application_pages_d (workspace_id);
--rollback not required

--changeset mlancast:create_index_sert_core.sg_application_pages_d_idx3 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:; stripComments:false
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedresult:0 select count(*) from dba_indexes where owner = upper('sert_core') and table_name = upper('sg_application_pages_d') and index_name = upper('sg_application_pages_d_idx3');
create index sert_core.sg_application_pages_d_idx3 on sert_core.sg_application_pages_d (workspace);
--rollback not required
