--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.builder_urls_1721795986865 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'BUILDER_URLS';
CREATE TABLE sert_core.builder_urls (
    builder_url_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    builder_url_key VARCHAR2(250) NOT NULL,
    component_name  VARCHAR2(250) NOT NULL,
    data_type_id    NUMBER,
    data_link       VARCHAR2(1000),
    description     VARCHAR2(4000),
    created_by      VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on      TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by      VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on      TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.builder_urls ADD CONSTRAINT builder_urls_pk PRIMARY KEY ( builder_url_id );
--rollback drop table sert_core.builder_urls;

--changeset mipotter:alter_table_sert_core.builder_urls_add_constraint_builder_urls_un_1721796960845 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'BUILDER_URLS_UN';
ALTER TABLE sert_core.builder_urls ADD CONSTRAINT builder_urls_un UNIQUE ( builder_url_key );
--rollback alter table sert_core.builder_urls drop constraint BUILDER_URLS_UN;
