--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.comments_1721796087167 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'COMMENTS';
CREATE TABLE sert_core.comments (
    comment_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_id      NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    comments         VARCHAR2(4000) NOT NULL,
    workspace_id     NUMBER NOT NULL,
    application_id   NUMBER NOT NULL,
    page_id          NUMBER,
    component_id     VARCHAR2(250),
    component_name   VARCHAR2(250),
    column_name      VARCHAR2(250),
    item_name        VARCHAR2(250),
    shared_comp_name VARCHAR2(250),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.comments ADD CONSTRAINT comments_pk PRIMARY KEY ( comment_id );
--rollback drop table sert_core.comments;
