--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.exceptions_1721796219376 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'EXCEPTIONS';
CREATE TABLE sert_core.exceptions (
    exception_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_id      NUMBER NOT NULL,
    rule_id          NUMBER NOT NULL,
    exception        VARCHAR2(4000) NOT NULL,
    workspace_id     NUMBER NOT NULL,
    application_id   NUMBER NOT NULL,
    page_id          NUMBER,
    component_id     VARCHAR2(250),
    column_name      VARCHAR2(250),
    item_name        VARCHAR2(250),
    shared_comp_name VARCHAR2(250),
    result           VARCHAR2(250) NOT NULL,
    reason           VARCHAR2(4000),
    current_value    VARCHAR2(4000),
    created_by       VARCHAR2(250) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    updated_by       VARCHAR2(250),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE,
    actioned_by      VARCHAR2(250),
    actioned_on      TIMESTAMP WITH LOCAL TIME ZONE,
    component_name   VARCHAR2(250)
)
LOGGING;

ALTER TABLE sert_core.exceptions ADD CONSTRAINT exceptions_pk PRIMARY KEY ( exception_id );
--rollback drop table sert_core.exceptions;

--changeset mipotter:alter_table_sert_core.exceptions_add_constraint_exceptions_un_1721796991114 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'EXCEPTIONS_UN';

ALTER TABLE sert_core.exceptions
    ADD CONSTRAINT exceptions_un UNIQUE ( rule_set_id,
                                          rule_id,
                                          workspace_id,
                                          application_id,
                                          page_id,
                                          component_id,
                                          column_name,
                                          item_name );
--rollback alter table sert_core.exceptions drop constraint EXCEPTIONS_UN;
