--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.prefs_1721796416146 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'PREFS';
CREATE TABLE sert_core.prefs (
    pref_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    pref_name   VARCHAR2(250) NOT NULL,
    pref_key    VARCHAR2(250) NOT NULL,
    pref_value  VARCHAR2(4000) NOT NULL,
    internal_yn VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    description VARCHAR2(4000),
    created_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.prefs ADD CONSTRAINT prefs_pk PRIMARY KEY ( pref_id );
--rollback drop table sert_core.prefs;

--changeset mipotter:alter_table_sert_core.prefs_add_constraint_prefs_internal_yn_1721797117084 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'PREFS_INTERNAL_YN';
ALTER TABLE sert_core.prefs
    ADD CONSTRAINT prefs_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );
--rollback alter table sert_core.prefs drop constraint PREFS_INTERNAL_YN;

--changeset mipotter:alter_table_sert_core.prefs_add_constraint_prefs_un_1721797128543 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'PREFS_UN';
ALTER TABLE sert_core.prefs ADD CONSTRAINT prefs_un UNIQUE ( pref_key );
--rollback alter table sert_core.prefs drop constraint PREFS_UN;
