--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.reserved_strings_1721796315979 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'RESERVED_STRINGS';
CREATE TABLE sert_core.reserved_strings (
    reserved_string_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    reserved_string      VARCHAR2(250) NOT NULL,
    reserved_string_key  VARCHAR2(250) NOT NULL,
    reserved_string_type VARCHAR2(250) NOT NULL,
    description          VARCHAR2(4000),
    active_yn            VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    created_by           VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on           TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by           VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on           TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.reserved_strings ADD CONSTRAINT reserved_strings_pk PRIMARY KEY ( reserved_string_id );

--rollback drop table sert_core.reserved_strings;

--changeset mipotter:alter_table_sert_core.reserved_strings_add_constraint_reserved_strings_un_1721797178550 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RESERVED_STRINGS_UN';
ALTER TABLE sert_core.reserved_strings ADD CONSTRAINT reserved_strings_un UNIQUE ( reserved_string_key,
                                                                         reserved_string_type );
--rollback alter table sert_core.reserved_strings drop constraint RESERVED_STRINGS_UN;

--changeset mipotter:alter_table_sert_core.reserved_strings_add_constraint_reserved_strings_active_yn_1721797170212 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RESERVED_STRINGS_ACTIVE_YN';
ALTER TABLE sert_core.reserved_strings
    ADD CONSTRAINT reserved_strings_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );
--rollback alter table sert_core.reserved_strings drop constraint RESERVED_STRINGS_ACTIVE_YN;
