--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.rule_sets_1721796602472 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'RULE_SETS';
CREATE TABLE sert_core.rule_sets (
    rule_set_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_set_type_id NUMBER NOT NULL,
    rule_set_name    VARCHAR2(250) NOT NULL,
    rule_set_key     VARCHAR2(250) NOT NULL,
    apex_version     NUMBER NOT NULL,
    active_yn        VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn      VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    description      VARCHAR2(4000),
    created_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by       VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.rule_sets ADD CONSTRAINT rule_sets_pk PRIMARY KEY ( rule_set_id );
--rollback drop table sert_core.rule_sets;

--changeset mipotter:alter_table_sert_core.rule_sets_add_constraint_rule_sets_active_yn_1721799322851 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_SETS_ACTIVE_YN';
ALTER TABLE sert_core.rule_sets
    ADD CONSTRAINT rule_sets_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );
--rollback alter table sert_core.rule_sets drop constraint RULE_SETS_ACTIVE_YN;

--changeset mipotter:alter_table_sert_core.rule_sets_add_constraint_rule_sets_internal_yn_1721799329054 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_SETS_INTERNAL_YN';
ALTER TABLE sert_core.rule_sets
    ADD CONSTRAINT rule_sets_internal_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );
--rollback alter table sert_core.rule_sets drop constraint RULE_SETS_INTERNAL_YN;

--changeset mipotter:alter_table_sert_core.rule_sets_add_constraint_rule_sets_un_1721799340007 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_SETS_UN';
ALTER TABLE sert_core.rule_sets ADD CONSTRAINT rule_sets_un UNIQUE ( rule_set_key, apex_version );
--rollback alter table sert_core.rule_sets drop constraint RULE_SETS_UN;
