--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.rule_severity_1721796625117 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'RULE_SEVERITY';
CREATE TABLE sert_core.rule_severity (
    rule_severity_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_severity_name VARCHAR2(250) NOT NULL,
    rule_severity_key  VARCHAR2(250) NOT NULL,
    seq                NUMBER NOT NULL,
    description        VARCHAR2(4000),
    created_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.rule_severity ADD CONSTRAINT rule_severity_pk PRIMARY KEY ( rule_severity_id );
--rollback drop table sert_core.rule_severity;

--changeset mipotter:alter_table_sert_core.rule_severity_add_constraint_rule_severity_un_1721799397336 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_SEVERITY_UN';
ALTER TABLE sert_core.rule_severity ADD CONSTRAINT rule_severity_un UNIQUE ( rule_severity_key );
--rollback alter table sert_core.rule_severity drop constraint RULE_SEVERITY_UN;
