--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.rule_criteria_types_1721796508391 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'RULE_CRITERIA_TYPES';
CREATE TABLE sert_core.rule_criteria_types (
    rule_criteria_type_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_criteria_type_name VARCHAR2(250) NOT NULL,
    rule_criteria_type_key  VARCHAR2(250) NOT NULL,
    active_yn               VARCHAR2(1) DEFAULT ON NULL 'Y' NOT NULL,
    internal_yn             VARCHAR2(1) DEFAULT ON NULL 'N' NOT NULL,
    description             VARCHAR2(4000),
    created_by              VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on              TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by              VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on              TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.rule_criteria_types ADD CONSTRAINT rule_criteria_types_pk PRIMARY KEY ( rule_criteria_type_id );
--rollback drop table sert_core.rule_criteria_types;

--changeset mipotter:alter_table_sert_core.rule_criteria_types_add_constraint_rule_criteria_types_active_yn_1721799047508 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_CRITERIA_TYPES_ACTIVE_YN';
ALTER TABLE sert_core.rule_criteria_types
    ADD CONSTRAINT rule_criteria_types_active_yn CHECK ( active_yn IN ( 'N', 'Y' ) );
--rollback alter table sert_core.rule_criteria_types drop constraint RULE_CRITERIA_TYPES_ACTIVE_YN;

--changeset mipotter:alter_table_sert_core.rule_criteria_types_add_constraint_rule_criteria_types_int_yn_1721799054527 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_CRITERIA_TYPES_INT_YN';
ALTER TABLE sert_core.rule_criteria_types
    ADD CONSTRAINT rule_criteria_types_int_yn CHECK ( internal_yn IN ( 'N', 'Y' ) );
--rollback alter table sert_core.rule_criteria_types drop constraint RULE_CRITERIA_TYPES_INT_YN;

--changeset mipotter:alter_table_sert_core.rule_criteria_types_add_constraint_rule_criteria_types_un_1721799061397 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'RULE_CRITERIA_TYPES_UN';
ALTER TABLE sert_core.rule_criteria_types ADD CONSTRAINT rule_criteria_types_un UNIQUE ( rule_criteria_type_key );
--rollback alter table sert_core.rule_criteria_types drop constraint RULE_CRITERIA_TYPES_UN;
