--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mipotter:create_table_sert_core.shared_comp_views_1721796704202 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'SERT_CORE' and table_name = 'SHARED_COMP_VIEWS';
CREATE TABLE sert_core.shared_comp_views (
    shared_comp_view_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    shared_comp_view    VARCHAR2(250) NOT NULL,
    shared_comp_type    VARCHAR2(250) NOT NULL,
    description         VARCHAR2(4000),
    created_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE sert_core.shared_comp_views ADD CONSTRAINT shared_comp_views_pk PRIMARY KEY ( shared_comp_view_id );
--rollback drop table sert_core.shared_comp_views;

--changeset mipotter:alter_table_sert_core.shared_comp_views_add_constraint_shared_comp_views_un_1721799603192 endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_constraints where owner = 'SERT_CORE' and constraint_name = 'SHARED_COMP_VIEWS_UN';
ALTER TABLE sert_core.shared_comp_views ADD CONSTRAINT shared_comp_views_un UNIQUE ( shared_comp_view );
--rollback alter table sert_core.shared_comp_views drop constraint SHARED_COMP_VIEWS_UN;
