prompt app_checksum: A8BF625380A5B1C6DCA63422D8883D4E62B09B32A02A5ECB109E237067AD587D
-------------------------------------------------------------------------------
-- Copyright (c) 2024,2025 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------
-- file_checksum: 62ED7E490C20168CEC03484EE414DF2199AE344B80A680043AB3F27E5754D707
prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/upload_exceptions_wizard.sql
@@application/shared_components/navigation/lists/reports_dg.sql
@@application/shared_components/navigation/lists/exceptions.sql
@@application/shared_components/navigation/lists/reports.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/evaluations.sql
@@application/shared_components/navigation/lists/evaluation_details_dialog.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/gis_evaluation_summary_report_template_docx.sql
@@application/shared_components/files/gis_attributes_master_report_template_docx.sql
@@application/shared_components/files/gis_exception_basic_docx.sql
@@application/shared_components/files/gis_evaluation_exception_report_template_docx.sql
@@application/shared_components/files/js_apex_sert_lib_min_js.sql
@@application/shared_components/files/is_evaluation_summary_report_template_docx.sql
@@application/shared_components/files/is_evaluation_exception_report_template_docx.sql
@@application/shared_components/files/is_attributes_master_report_template_docx.sql
@@application/shared_components/files/is_evaluation_detail_report_template_docx.sql
@@application/shared_components/files/gis_evaluation_detail_report_template_docx.sql
@@application/shared_components/files/js_apex_sert_lib_js.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/allow_for_evaluation.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/set_evaluation_results_items.sql
@@application/shared_components/logic/application_processes/saveapexlink.sql
@@application/shared_components/logic/application_items/g_aop_url.sql
@@application/shared_components/logic/application_items/g_apex_version.sql
@@application/shared_components/logic/application_items/g_application_id.sql
@@application/shared_components/logic/application_items/g_button_link.sql
@@application/shared_components/logic/application_items/g_category_name.sql
@@application/shared_components/logic/application_items/g_email_from.sql
@@application/shared_components/logic/application_items/g_eval_result_id.sql
@@application/shared_components/logic/application_items/g_eval_title.sql
@@application/shared_components/logic/application_items/g_icon.sql
@@application/shared_components/logic/application_items/g_log_key.sql
@@application/shared_components/logic/application_items/g_oci_bucket_name.sql
@@application/shared_components/logic/application_items/g_oci_bucket_namespace.sql
@@application/shared_components/logic/application_items/g_oci_bucket_output_folder.sql
@@application/shared_components/logic/application_items/g_oci_bucket_template_folder.sql
@@application/shared_components/logic/application_items/g_oci_docgen_function_ocid.sql
@@application/shared_components/logic/application_items/g_oci_region_name.sql
@@application/shared_components/logic/application_items/g_release_version.sql
@@application/shared_components/logic/application_items/g_rule_name.sql
@@application/shared_components/logic/application_items/g_stale_eval.sql
@@application/shared_components/logic/application_items/g_workspace_id.sql
@@application/shared_components/logic/application_items/g_workspace_name.sql
@@application/shared_components/logic/application_computations/g_application_id.sql
@@application/shared_components/logic/application_computations/g_stale_eval.sql
@@application/shared_components/logic/application_computations/g_email_from.sql
@@application/shared_components/logic/application_computations/g_release_version.sql
@@application/shared_components/logic/application_computations/g_aop_url.sql
@@application/shared_components/logic/application_computations/g_oci_region_name.sql
@@application/shared_components/logic/application_computations/g_oci_docgen_function_ocid.sql
@@application/shared_components/logic/application_computations/g_oci_bucket_namespace.sql
@@application/shared_components/logic/application_computations/g_oci_bucket_name.sql
@@application/shared_components/logic/application_computations/g_oci_bucket_output_folder.sql
@@application/shared_components/logic/application_computations/g_oci_bucket_template_folder.sql
@@application/shared_components/logic/application_computations/g_workspace_name.sql
@@application/shared_components/logic/application_computations/g_apex_version.sql
@@application/shared_components/logic/application_computations/g_workspace_id.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/category_lov.sql
@@application/shared_components/user_interface/lovs/rules_lov.sql
@@application/shared_components/user_interface/lovs/rules_lov_exceptions_ar.sql
@@application/shared_components/user_interface/lovs/rules_lov_raise_exceptions.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/reports/report_layouts/is_evaluation_summary_report_template.sql
@@application/shared_components/reports/report_layouts/is_evaluation_detail_report_template.sql
@@application/shared_components/reports/report_layouts/is_evaluation_exception_report_template.sql
@@application/shared_components/reports/report_layouts/is_attributes_master_report_template.sql
@@application/shared_components/security/authentications/builder_extension_authn.sql
@@application/shared_components/plugins/dynamic_action/be_apexrnd_aop_da.sql
@@application/shared_components/plugins/template_component/theme_42_avatar.sql
@@application/shared_components/plugins/template_component/theme_42_badge.sql
@@application/shared_components/plugins/template_component/theme_42_button.sql
@@application/shared_components/plugins/template_component/theme_42_comments.sql
@@application/shared_components/plugins/template_component/theme_42_content_row.sql
@@application/shared_components/plugins/template_component/theme_42_media_list.sql
@@application/shared_components/plugins/template_component/theme_42_timeline.sql
@@application/shared_components/plugins/process_type/com_oracle_apex_docgen.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00005.sql
@@application/pages/page_00010.sql
@@application/pages/page_00020.sql
@@application/pages/page_00030.sql
@@application/pages/page_00040.sql
@@application/pages/page_00042.sql
@@application/pages/page_00045.sql
@@application/pages/page_00050.sql
@@application/pages/page_00060.sql
@@application/pages/page_00070.sql
@@application/pages/page_00080.sql
@@application/pages/page_00090.sql
@@application/pages/page_00100.sql
@@application/pages/page_00200.sql
@@application/pages/page_00210.sql
@@application/pages/page_00220.sql
@@application/pages/page_00230.sql
@@application/pages/page_00240.sql
@@application/pages/page_00250.sql
@@application/pages/page_00260.sql
@@application/pages/page_00270.sql
@@application/pages/page_00280.sql
@@application/pages/page_00302.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
