--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024-2026 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mlancast:create_table_sert_core.sg_etl_tasks endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_tables where owner = upper('sert_core') and table_name = upper('sg_etl_tasks');
-- Defines the individual PL/SQL procedures (tasks) that run within an ETL pipeline, including their execution phase.
create table sert_core.sg_etl_tasks (
    task_id                     number generated by default on null as identity (start with 1),
    pipeline_id                 number not null,
    task_phase                  number not null,
    task_name                   varchar2(128) not null,
    plsql_procedure_name        varchar2(386) not null,
    required_load_type          varchar2(20),
    is_active                   char(1) default 'Y' not null,
    constraint sg_etl_tasks_pk
        primary key (task_id),
    constraint sg_etl_tasks_uk
        unique (pipeline_id, task_phase, task_name),
    constraint sg_etl_tasks_cc1
        check (is_active in ('Y', 'N')),
    constraint sg_etl_tasks_cc2
        check (required_load_type is null or required_load_type in ('FULL', 'INCREMENTAL'))
);
--rollback drop table sert_core.sg_etl_tasks cascade constraints purge;

--changeset mlancast:create_index_sert_core.sg_etl_tasks_fk_idx endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_indexes where owner = upper('sert_core') and index_name = upper('sg_etl_tasks_fk_idx');
create index sert_core.sg_etl_tasks_fk_idx on sert_core.sg_etl_tasks (pipeline_id);
--rollback not required
