--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024-2026 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mlancast:create_table_sert_core.sg_etl_pipelines endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_tables where owner = upper('sert_core') and table_name = upper('sg_etl_pipelines');
-- Stores metadata for the overall ETL pipeline (e.g. pipeline name, default load type).
create table sert_core.sg_etl_pipelines (
    pipeline_id                 number generated by default on null as identity (start with 1),
    pipeline_name               varchar2(128) not null,
    job_description             varchar2(4000),
    load_type                   varchar2(20) default 'FULL' not null,
    is_active                   char(1) default 'Y' not null,
    constraint sg_etl_pipelines_pk
        primary key (pipeline_id),
    constraint sg_etl_pipelines_uk
        unique (pipeline_name),
    constraint sg_etl_pipelines_cc1
        check (is_active in ('Y', 'N')),
    constraint sg_etl_pipelines_cc2
        check (load_type in ('FULL', 'INCREMENTAL'))
);
--rollback drop table sert_core.sg_etl_pipelines cascade constraints purge;
