--liquibase formatted sql
-------------------------------------------------------------------------------
-- Copyright (c) 2024-2026 Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v 1.0 as shown
-- at https://oss.oracle.com/licenses/upl/
--------------------------------------------------------------------------------

--changeset mlancast:create_table_sert_core.sg_etl_task_log endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_tables where owner = upper('sert_core') and table_name = upper('sg_etl_task_log');
-- Logs the detailed execution, metrics, and status of each individual task within an ETL run.
create table sert_core.sg_etl_task_log (
    task_log_id                 number generated by default on null as identity (start with 1),
    log_id                      number not null,
    task_id                     number not null,
    start_timestamp             timestamp(6) with time zone not null,
    end_timestamp               timestamp(6) with time zone,
    status                      varchar2(20) not null,
    rows_changed                number,
    status_message              varchar2(4000),
    error_message               varchar2(4000),
    constraint sg_etl_task_log_pk
        primary key (task_log_id),
    constraint sg_etl_task_log_cc1
        check (status in ('RUNNING', 'COMPLETED', 'FAILED'))
);
--rollback drop table sert_core.sg_etl_task_log cascade constraints purge;

--changeset mlancast:create_index_sert_core.sg_etl_task_log_fk1_idx endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_indexes where owner = upper('sert_core') and index_name = upper('sg_etl_task_log_fk1_idx');
create index sert_core.sg_etl_task_log_fk1_idx on sert_core.sg_etl_task_log (log_id);
--rollback not required

--changeset mlancast:create_index_sert_core.sg_etl_task_log_fk2_idx endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from dba_indexes where owner = upper('sert_core') and index_name = upper('sg_etl_task_log_fk2_idx');
create index sert_core.sg_etl_task_log_fk2_idx on sert_core.sg_etl_task_log (task_id);
--rollback not required
